### ISSUE TITLE
Endzeit wird automatisch 01:00 wen keine Zeit eingegeben wird.

### ISSUE THREAD

**Issue by Floxn** [contao/calendar-bundle#10]
Wird einer Veranstaltung eine Startzeit gegeben muss wohl auch eine Endzeit eingegeben werden. 
Möchte man nun aber keine Endzeit im Frontend ausgeben löscht man den Eintrag ja wieder im Backend.
Nach dem Speichern steht dann nun aber ein 01:00 und wird auch so im Frontend als Endzeit ausgegeben.

Im Frontend erscheint nur keine Endzeit, wenn Endzeit = Startzeit. 
Ist denn eine Endzeit zwingend?

Reproduzierbar in der Demo:
- Neues Event anlegen.
- Haken bei "Zeit hinzufügen" setzen
- Starzeit eintragen
- Endzeit löschen
- speichern
- Endzeit ansehen

**Comment by Floxn** [comment]
Nachtrag:
Den Author wird das vermutlich verwirren, wenn die gleiche Zeit wie bei Startzeit drin steht. 
Wenn es keine offizielle Endzeit gibt, sollte diese auch leer bleiben.

**Comment by Aybee** [comment]
Ich habe letztens erst überlegt, warum ich in der dcaconfig seit Jahren das hier drin habe.
```php
/** Events */
// Set endtime default to empty
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['endTime']['default'] = NULL;
```
Evtl. hat das mit diesem Problem zu tun und wäre eine Lösung.

**Comment by Floxn** [comment]
Das scheint wohl nicht mehr zu funktionieren. Danach gibt es noch ein save_callback und führt folgendes aus.

> 	public function setEmptyEndTime($varValue, DataContainer $dc)
	{
		if ($varValue === '')
		{
			$varValue = $dc->activeRecord->startTime;
		}

		return $varValue;
	}

Irgendwas mussten die Core-Entwickler sich da ja gedacht haben :)

**Comment by leofeyer** [comment]
> Ist denn eine Endzeit zwingend?

Ja, das Feld ist zwingend (vgl. contao/core#1922). Deswegen haben wir ja "Use the same value for start and end time to create an open-ended event." als Erklärung unter das Feld geschrieben.

**Comment by Aybee** [comment]
Ist evtl. zwingend (programmiertechnisch gesehen, deshalb ein Callback, welcher das Feld immer irgendwie ausfüllt) aber nicht mandatory.

Schön, intuitiv und logisch finde ich das übrigens nicht, so einen Satz wie
> Use the same value for start and end time to create an open-ended event.

Sollte ja eigentlich leer bleiben dürfen, wenn man keine Endzeit weiß. Wenn da steht 
```
Datum 01.01.2018 
Start 20:00 
Ende 20:00
```
dann würde das Event eigentlich exakt 0 Sekunden dauern. Oder gilt es sogar bis zum 02.01 um 20:00?

Ein leeres Feld müsste im Programmcode eigentlich aufgefangen und richtig interpretiert werden können. Aber ich kann verstehen, dass man dies jetzt nicht unbedingt ändern möchte, da die Logik dieser Events mit den ganzen Daten und Zeiten, Wiederholungen usw. ganz schön komplex ist und im Laufe der Jahre oftmals überarbeitet wurde, da immer wieder irgendwelche Bugs auftauchten.

**Comment by Floxn** [comment]
Ok, dann ist es kein Fehler sondern gewollt. Damit kann man umgehen und in den Schulungen so kommunizieren.

Danke für die Antworten.

**Comment by leofeyer** [comment]
Allerdings war der `save_callback` kaputt, der die Endzeit automatisch auf die Startzeit setzt, wenn das Feld leer bleibt. Repariert in 97bb090e2196d186dc91a7c81d2854809871cf48.
