### ISSUE TITLE
Extend/improve event microdata (schema.org)

### ISSUE THREAD

**Issue by CMSworker** [contao/calendar-bundle#12]
Hello Contao team,

to get the events shown in Google search results, at least the "location" field should be added with microdata, because this is a required field (from Google perspective). Currently the location is only published as plain HTML text (at least in the [Demo](https://demo.contao.org/en/event-detail/contao-north-day.html)).

Please also see the errors in the [Google Structured Data Testing Tool with Contao example event page](https://search.google.com/structured-data/testing-tool?hl=de#url=https%3A%2F%2Fdemo.contao.org%2Fen%2Fevent-detail%2Fcontao-north-day.html) - the missing location is throwing an error.

Besides that: Is there a reason why the event pages in Contao are so... "basic"? To have a useful events component with correct microdata support, it should be possible to prepare different locations in a separate content table (to avoid duplicate content in the CMS and the microdata could be used directly from the locations entries) and also have some more fields eg for performers, [door time](http://schema.org/doorTime), [event status](http://schema.org/eventStatus) and much more, see [event on schema.org](http://schema.org/Event) with many examples... Also an option to select the type of the event would be usefull (MusicEvent, BusinessEvent, ChildrenEvent, Festival, SportsEvent...)

Or is this all ment to be added by external plugins and extensions? If so, why is the calendar and events module part of the core and not an optional module? (I'm not against the calendar module, I just want to know why it is so basic and rudimentary).

Thank you all for your great Contao work and effords!

**Comment by CMSworker** [comment]
I made a pull request #17 for adding the location name microdata.

Please note that according to the [Google Dev Docs](https://developers.google.com/search/docs/data-types/events) the address is also required. Currently there are no input fields available in the event/calendar module for an address. I suggest to also add at least an input field for the city.

So the template output could be changed from
`<p class="location" itemprop="location" itemscope itemtype="http://schema.org/Place"><?= $this->locationLabel ?>: <span itemprop="name"><?= $this->location ?></span></p>`

to

`<p class="location" itemprop="location" itemscope itemtype="http://schema.org/Place"><?= $this->locationLabel ?>: <span itemprop="name"><?= $this->location ?></span>, <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"><span itemprop="addressLocality">City</span></span></p>`

**Comment by leofeyer** [comment]
See #17.
