### ISSUE TITLE
make enclosure sortable

### ISSUE THREAD

**Issue by mpitz** [contao/calendar-bundle#16]
the enclosure should be sortable like the downloads in the content

**Comment by leofeyer** [comment]
Why? They are only attachments, aren't they?

**Comment by asaage** [comment]
Some people don't use content for news/events.
I think for consistency-reasons it would just be nice if enclosure's behave the same as downloads (don't they share the same template?)

**Comment by mpitz** [comment]
@asaage: correct.

And in my case I'am using both. In the main col are all the details about the event and some info-material. In the aside are general info-downloads for the event. And so far, they're not sortable.

**Comment by leofeyer** [comment]
Implemented in cf3800b00eac6b6b449140eb3e1fc61f720f0062.
