### ISSUE TITLE
URL-Parameter gehen nicht bei Eventlist Anzeigeformat "Alle Events"

### ISSUE THREAD

**Issue by joeherold** [contao/calendar-bundle#20]
Wenn ich ein Modul vom Typ Eventliste erstelle und als Anzeigeformat "Alle Events" Wähle, dann gehen die URL-Parameter vom Event-Menü nicht.

Ist das so erwünscht ? Bin heute das erste mal drüber gestolpert...

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?
