### ISSUE TITLE
external redirect will not be linked in template

### ISSUE THREAD

**Issue by fritzmg** [contao/calendar-bundle#21]
### Abridged reproduction:

1. Create a new event.
2. Set __Redirect target__ to _External URL_.
3. Set __Link target__ to `https://www.google.com/`.
4. Create an _Event list_ module and set the __Event template__ to `event_teaser`.
5. Integrate the module somewhere in the front end.
6. Open the front end.

The headline of the created event will not be linked. Also there will be no _Read more…_ link. Thus you are unable to actually go the the external URL.

Tested with Contao 4.4.12. Same problem exists in Contao 3.5.31 probably.

### Cause

This is caused by [these lines](https://github.com/contao/calendar-bundle/blob/4.4.12/src/Resources/contao/modules/ModuleEventlist.php#L290-L294):
```php
// Show the teaser text of redirect events (see #6315)
if (\is_bool($event['details']))
{
    $objTemplate->hasDetails = false;
}
```

This is a problem for the `event_teaser` template, since it will only show links when `hasDetails` is `true`. The other templates like `event_list` or `event_upcoming` _always_ create a link, regardless of `hasDetails`.

The current behaviour is inconsistent with the news module. In the news module, the headline is linked when it is an external redirect and the default `news_latest` template shows a `Read more…` link as well, when the news entry is an external redirect.

**Comment by leofeyer** [comment]
Fixed in dab55ac22b16ff599ecee75894fc34c183f3eb69.
