### ISSUE TITLE
Mixed calendars in eventlist module shows always "first", "last" and "even" class in html markup

### ISSUE THREAD

**Issue by mpitz** [contao/calendar-bundle#24]
If you mix calendars in the eventlist module the classes in the html markup are always "first" and "last". But the first element should have the class "first" and the last element "last" independent of the mixed calendars.

![image](https://user-images.githubusercontent.com/6831223/35768045-78999646-08f6-11e8-8659-62ee8114f2be.png)

By the way. The even and odd classes are also set wrong. It's every time "even".

Here are the settings from the module:

![image](https://user-images.githubusercontent.com/6831223/35768108-4b1bb856-08f7-11e8-9ac2-39b0ce62cbfa.png)

Contao 4.4.13

**Comment by leofeyer** [comment]
I cannot reproduce this in the official demo.

<img width="849" alt="" src="https://user-images.githubusercontent.com/1192057/36193930-1159c21a-1168-11e8-9ca7-aed377b69c97.png">

How do I reproduce this on demo.contao.org?

**Comment by mpitz** [comment]
Sorry for the late feedback.

I can reproduce this on demo.contao.org:

- Add 2 calendars and fill them up with 2 and 1 event in the past (additional: add time Option):
![backend-events](https://user-images.githubusercontent.com/6831223/42075772-ca5b291a-7b72-11e8-8ee4-19a2e55e4405.png)

- Add a module (Event list) with the following settings:
![backend-event-module](https://user-images.githubusercontent.com/6831223/42075786-d3776eaa-7b72-11e8-9ae2-a968a4c39900.png)

- Add the module to the page layout (2 columns):
![backend-page-layout-2-columns](https://user-images.githubusercontent.com/6831223/42075809-f31a1a14-7b72-11e8-85db-77bd473a711f.png)

Than you can explore in the frontend:
![frontend](https://user-images.githubusercontent.com/6831223/42075825-0a265d58-7b73-11e8-8d56-b3b3ed86ef8a.png)

And you can see the mentioned classes:
![dev-tools](https://user-images.githubusercontent.com/6831223/42075847-1d516864-7b73-11e8-9e77-c249c0f46124.png)

**Comment by leofeyer** [comment]
Even/odd is reset after each header, so the generated markup is fine. If you have more than one event per day, the CSS classes will be applied accordingly.
