### ISSUE TITLE
Google Structured data: Image? Or associatedMedia?

### ISSUE THREAD

**Issue by richardhj** [contao/calendar-bundle#29]
The Google Test Tool for strucutred data (https://search.google.com/structured-data/testing-tool/u/0/?hl=de#url=https%3A%2F%2Fwww.alfeld-rockt.de%2F) has some errors with my event.

The one I want to address with this issue: Google wants one `image` tag, however it does not want the `associatedImage` tag.
Do we want to change labels?

![screen shot 2018-05-06 at 18 35 05](https://user-images.githubusercontent.com/1284725/39675507-3bfdf836-515c-11e8-821e-0121a5a2c16b.png)
![screen shot 2018-05-06 at 18 34 54](https://user-images.githubusercontent.com/1284725/39675508-3c1a3b54-515c-11e8-9b9d-ecd956284bee.png)

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
[associatedMedia](https://schema.org/associatedMedia) is a property of the [CreativeWork](https://schema.org/CreativeWork) type and can not be used on events.

It should be safe to change from `itemprop="associatedMedia"` to `itemprop="image"` in [image.html5](https://github.com/contao/core-bundle/blob/504d8ed7c14a8e135def5722e47ffa1dc7c4d6ed/src/Resources/contao/templates/image/image.html5) as every type supports the [image](https://schema.org/image) property.

Maybe @marcobiedermann knows more about that as he added many schema tags in contao/core#7780

**Comment by marcobiedermann** [comment]
Unfortunately the documentation on Schema.org does not provide much context.
From what I have read on other forums, I think it is safe to remove `itemprop="associatedMedia"` entirely.
I would not change it to `itemprop="image"` because this is used for the `<img>` tag itself.

**Comment by richardhj** [comment]
I guess we can't remove `itemprop="associatedMedia"` without giving the `itemtype="http://schema.org/ImageObject"` tag to another element.

**Comment by ausi** [comment]
We should probably remove `itemprop="associatedMedia"`, `itemtype="http://schema.org/ImageObject"` and `itemscope` from the *image.html5* template. `itemprop="image"` on the `<img>` element gets recognized as image, so there is no need for an explicit `ImageObject` I think.

**Comment by leofeyer** [comment]
Removed in contao/core-bundle@73c16c968a2f970241c987548aa11bf66257ee29.

The ` itemprop="contentUrl"` is still in the templates (e.g. https://github.com/contao/core-bundle/blob/4.4/src/Resources/contao/templates/image/image.html5#L5). Is this correct?

**Comment by ausi** [comment]
Both `itemprop="contentUrl"` and `itemprop="caption"` have to be removed IMO

**Comment by leofeyer** [comment]
Removed in contao/core-bundle@f3ae9d209a684d90acacf558e84d566249bfcdb7.
