### ISSUE TITLE
Hide running events (Laufende Events ausblenden) has no effect

### ISSUE THREAD

**Issue by rustykowski** [contao/calendar-bundle#30]
Unabhängig, ob in der Modulkonfiguration dieses Flag aktiviert ist oder nicht, werden laufende Events immer angezeigt. 
Beim Format ist ansonsten eingestellt: "All upcoming events" (Alle zukünftigen Events).
Getestet unter Contao 4.4.18 und 4.5.8 in der Contao-Demo.

**Comment by leofeyer** [comment]
Wie genau lässt sich das Problem reproduzieren?

**Comment by rustykowski** [comment]
1. Ein Event mit dem heutigen Datum anlegen (optional mit Startzeit heute Morgen und Endzeit heute Abend) . Event veröffentlichen => Event erscheint im FE im Footer.
2. Das Modul "Calendar - Event list footer" bearbeiten und "Hide running events" aktivieren => Event erscheint immer noch im Footer

**Comment by leofeyer** [comment]
Bitte ändere das Event mal testweise so dass es gestern beginnt und morgen endet. Wird es dann immer noch angezeigt?

**Comment by rustykowski** [comment]
Ja, es wird immer noch angezeigt.

**Comment by leofeyer** [comment]
Das Flag wurde ursprünglich nur für wiederholte Events eingeführt (siehe contao/core#8497). Wir könnten es natürlich auch auf einzelne Events anwenden, was jedoch eine Änderung des Verhaltens wäre und somit erst in die nächste Feature-Version käme.

@contao/developers @fritzmg Irgendwelche Einwände?

**Comment by fritzmg** [comment]
Keine Einwände von mir :). Sollte nicht nur für wiederholte Events gelten.

**Comment by rustykowski** [comment]
Ja, das wäre sinnvoll. Um was auch immer es geht (Seminare, Konferenzen, Workshops etc.), häufig ist es erwünscht, das Event nicht mehr zu promoten, wenn es bereits begonnen hat.

**Comment by leofeyer** [comment]
Implementiert in 96e66a61bb03c7c7a0056e02f0a2b801bfcf7598.
