### ISSUE TITLE
Endzeit wird automatisch geleert, wenn 01:00 Uhr eingegeben wird

### ISSUE THREAD

**Issue by Total-Reality** [contao/calendar-bundle#40]
Wenn bei einer Veranstaltung die Endzeit auf 01:00 Uhr gesetzt wird, dann wird das nach dem Speichern einfach wieder entfernt.
Das hängt wohl hiermit zusammen:
https://github.com/contao/calendar-bundle/blob/4.x/src/Resources/contao/dca/tl_calendar_events.php#L777

Das ist echt ungünstig, da das Event nun mal leider um 01:00 Uhr endet. Also was nun machen? Kann ja schlecht einstellen, dass es dann 01:01 Uhr endet :D

Das ganze ist reproduzierbar in der Demo. Unsere Installation ist übrigens auch Contao 4.9

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/contao/issues/3376
