### ISSUE TITLE
FR: handle running events in event-list module more flexible

### ISSUE THREAD

**Issue by asaage** [contao/calendar-bundle#5]
There are different opinions on how to deal with running events as they are not "upcomming" and not "past".
i suggest to add a checkbox as described [here](https://github.com/contao/core/issues/8497#issuecomment-250473095)

**Comment by leofeyer** [comment]
As discussed in Mumble on October 6th, there should be a setting "show running events as upcoming" in the event settings, which is then considered in the `CalendarEventsModel::findCurrentByPid()` method.

**Comment by asaage** [comment]
kind of tricky...
in case this will be realised with an [event-attribute](https://github.com/contao/core/issues/8497#issuecomment-255352117)
i'd appreciate an aditional eventlist-format "**running events**" besides **all**, **upcomming** and **past**
 to be able to have closed events that already started not to show up as upcomming in one list but in a separate one as currently running.

**Comment by leofeyer** [comment]
See #8497.
